// @ts-check
import tailwind from "@tailwindcss/vite";
import preact from "@astrojs/preact";
import { defineConfig } from "astro/config";

// s03.C webmail shell. Static output (Cloudflare Pages, the same proven path as
// the marketing site). The authenticated mail surfaces mount as Preact islands —
// the "SPA-in-an-island" shape from arch.md §1.
export default defineConfig({
  site: "https://mail.bullmoose.cc",
  integrations: [preact()],

  // Tailwind v4 (s07 nav spike). A Vite plugin rather than an Astro
  // integration — v4 dropped the integration in favour of this.
  //
  // It emits an EXTERNAL stylesheet, which matters for the CSP below: an
  // external sheet from our own origin is covered by `default-src 'self'`
  // and needs no policy change. That is most of why Tailwind is a safe
  // adoption here and Headless UI is not — Headless UI sets inline `style`
  // attributes for its transitions and positioning, which would force
  // `'unsafe-inline'` into style-src on the authenticated surface.
  vite: { plugins: [tailwind()] },

  // CSP is the second half of the XSS defence (arch.md §4): sanitization strips
  // the payload, and this makes sure a payload that somehow survived has no
  // script to run and nowhere to phone home to.
  //
  // ⚠️ Generated by Astro, NOT hand-written in the page. A hand-written
  // `script-src 'self'` looks stricter but breaks the app outright: Astro's
  // hydration bootstrap for `client:only` is an INLINE script, so the island
  // never mounts and the page renders an empty body — which `astro build` and
  // the unit tests both report as success. Astro emits the per-build hashes for
  // its own inline scripts and styles alongside these directives, which is the
  // only way to keep `'unsafe-inline'` out of `script-src`.
  security: {
    csp: {
      directives: [
        "default-src 'self'",
        // Remote images are a per-message opt-in the user makes deliberately
        // (see lib/mail/sanitize.ts); blob:/data: cover inline attachments.
        "img-src 'self' https: data: blob:",
        // The JMAP API and the /api/ws push socket.
        "connect-src 'self' https: wss:",
        "frame-src 'none'",
        "object-src 'none'",
        "base-uri 'none'",
        "form-action 'none'",
      ],
    },
  },
});
