package authkey

import (
	"encoding/hex"
	"encoding/json"
	"os"
	"path/filepath"
	"testing"
)

// conformance/login-key.json, as generated by conformance/vectors.ts from the
// LIVE auth-core TypeScript. Nothing here is transcribed: a hand-written vector
// records what someone believed, which is the thing being checked (vectors.ts's
// header).
type loginVector struct {
	Algo       string `json:"algo"`
	Iterations int    `json:"iterations"`
	KeyBits    int    `json:"keyBits"`
	SaltLabel  string `json:"saltLabel"`
	Vectors    []struct {
		Name     string `json:"name"`
		Note     string `json:"note"`
		Email    string `json:"email"`
		Password string `json:"password"`
		SaltHex  string `json:"saltHex"`
		LoginKey string `json:"loginKey"`
	} `json:"vectors"`
}

// TestDeriveLoginKeyMatchesTheConformanceVector is THE test of this wave.
//
// deriveLoginKey is a cross-language coupling with no compiler to check it
// (arch.md §5). A mismatch does not surface as a crash or a 500 — the server
// compares a hash of the derived key, so a Go CLI that derives it differently
// gets a plain 401 and tells the user their password is wrong. They will then
// reset a password that was never wrong. That is why the vector exists, and why
// this test asserts the SALT separately from the key: a salt mismatch localises
// the fault to email normalisation, a key mismatch with a matching salt
// localises it to the stretch.
func TestDeriveLoginKeyMatchesTheConformanceVector(t *testing.T) {
	v := loadVector(t)

	// Parameters first. auth-core:317 exports LOGIN_SALT_LABEL specifically so
	// the vector can RECORD the parameters rather than restate them: a port that
	// matches today's golden keys but hard-codes different parameters passes now
	// and diverges the moment the vector is regenerated.
	if v.Algo != "client-pbkdf2-sha256-v1" {
		t.Errorf("vector algo = %q; this port implements client-pbkdf2-sha256-v1", v.Algo)
	}
	if v.Iterations != Iterations {
		t.Errorf("iterations: vector says %d, this port uses %d", v.Iterations, Iterations)
	}
	if v.KeyBits != KeyBytes*8 {
		t.Errorf("key length: vector says %d bits, this port derives %d", v.KeyBits, KeyBytes*8)
	}
	if v.SaltLabel != SaltLabel {
		t.Errorf("salt label: vector says %q, this port uses %q", v.SaltLabel, SaltLabel)
	}

	if len(v.Vectors) == 0 {
		t.Fatal("no cases in conformance/login-key.json — the oracle is empty, so this test proves nothing")
	}
	for _, c := range v.Vectors {
		t.Run(c.Name, func(t *testing.T) {
			t.Parallel() // 600k iterations per case; the cases are independent
			if got := hex.EncodeToString(LoginSalt(c.Email)); got != c.SaltHex {
				t.Fatalf("salt for %q\n  got  %s\n  want %s\n  what this catches: %s",
					c.Email, got, c.SaltHex, c.Note)
			}
			got, err := DeriveLoginKey(c.Email, c.Password)
			if err != nil {
				t.Fatalf("DeriveLoginKey: %v", err)
			}
			if got != c.LoginKey {
				t.Fatalf("loginKey for %q\n  got  %s\n  want %s\n  what this catches: %s",
					c.Email, got, c.LoginKey, c.Note)
			}
		})
	}
}

// TestMixedCaseEmailDerivesOneKey states the vector's most consequential pair as
// a property rather than as two golden strings: the salt lower-cases the address,
// so how the user typed it cannot change the key. A port that skips the
// lower-casing fails login with a correct password.
func TestMixedCaseEmailDerivesOneKey(t *testing.T) {
	lower, err := DeriveLoginKey("eric@bullmoose.cc", "hunter2")
	if err != nil {
		t.Fatal(err)
	}
	upper, err := DeriveLoginKey("Eric@Bullmoose.CC", "hunter2")
	if err != nil {
		t.Fatal(err)
	}
	if lower != upper {
		t.Errorf("case of the address changed the key:\n  %s\n  %s", lower, upper)
	}
}

func loadVector(t *testing.T) loginVector {
	t.Helper()
	raw, err := os.ReadFile(conformancePath(t, "login-key.json"))
	if err != nil {
		t.Fatalf("reading the conformance vector: %v", err)
	}
	var v loginVector
	if err := json.Unmarshal(raw, &v); err != nil {
		t.Fatalf("conformance/login-key.json is not the expected shape: %v", err)
	}
	return v
}

// conformancePath finds conformance/<name> by walking up from the test's
// directory. Unlike the schema drift check, a missing vector is FATAL: this test
// has no other oracle, so silently skipping it would leave the port's single
// most dangerous divergence unchecked.
func conformancePath(t *testing.T, name string) string {
	t.Helper()
	dir, err := os.Getwd()
	if err != nil {
		t.Fatal(err)
	}
	for {
		p := filepath.Join(dir, "conformance", name)
		if _, err := os.Stat(p); err == nil {
			return p
		}
		parent := filepath.Dir(dir)
		if parent == dir {
			t.Fatalf("conformance/%s not found above %s — regenerate with `npm run gen:conformance`", name, dir)
		}
		dir = parent
	}
}
