/**
 * The generator behind `conformance/*.json` — s08 T1, `arch.md` §5.
 *
 * `packages/cli` is being ported to Go. Three things the CLI and the platform
 * agree about are enforced today by nothing but code review, because across
 * languages there is no import for a compiler to check:
 *
 *   deriveLoginKey    a mismatch presents as "wrong password" and sends you to
 *                     fix something that is not broken
 *   the scope set     a mismatch is a token that looks minted and silently
 *                     does nothing — or, worse, one that permits too much
 *   EXIT / JMAP_EXIT  a mismatch breaks every script that branches on `$?`
 *
 * So each becomes a file both sides read. **Everything below is derived by
 * CALLING the live TypeScript.** Nothing is transcribed: a hand-written vector
 * records what someone believed, which is the thing being checked.
 *
 * This module is deliberately outside every tsc program — it imports
 * `@bullmoose/auth-core` (workers-typed) and `packages/cli/src/io.ts`
 * (Node-typed) in one file, and no single compiler configuration types both.
 * That boundary is precisely why these vectors exist; `vectors.test.ts` runs
 * this under vitest, which needs no such program. See the note in
 * `tsconfig.json` about why cli and webmail are typechecked separately.
 *
 * Regenerate with `npm run gen:conformance`. `vectors.test.ts` fails if the
 * committed bytes and this generator disagree, so drift is a red build.
 */

import {
  DEFAULT_LOGIN_SCOPES,
  LOGIN_KEY_ALGO,
  LOGIN_KEY_ITERATIONS,
  LOGIN_SALT_LABEL,
  MAIL_SCOPES,
  REALM_SCOPES,
  SELF_SERVICE_SCOPES,
  TOKEN_SCOPES,
  deriveLoginKey,
  hasScope,
  loginSaltHex,
} from "@bullmoose/auth-core";
// Extensionless and relative: the CLI is a separate workspace with its own
// Node-typed tsconfig, and this file is in neither program (see the header).
import { EXIT, JMAP_EXIT, exitCodeForJmapType } from "../packages/cli/src/io";

/** The committed artefacts, in the order `gen:conformance` writes them. */
export const FILES = ["exit-codes.json", "login-key.json", "scopes.json"] as const;
export type VectorFile = (typeof FILES)[number];

const EDIT_WARNING =
  "GENERATED by conformance/vectors.ts — do not edit; run `npm run gen:conformance`.";

// ───────────────────────────── stable bytes ─────────────────────────────────

/**
 * JSON with every object key sorted, recursively.
 *
 * `JSON.stringify` preserves insertion order, so how the generator happened to
 * build an object would leak into the committed bytes and a harmless
 * refactor — reordering a literal, spreading in a different order — would show
 * up as drift. A drift test that flaps gets deleted by whoever it wakes up, so
 * the ordering has to be a property of the format rather than of the code.
 *
 * `inlineFrom` is the depth at which values collapse onto one line. `scopes.json`
 * is 2,379 cases; pretty-printing each over six lines makes a 24k-line file that
 * no reviewer will ever open.
 */
function stableJson(value: unknown, inlineFrom = Number.POSITIVE_INFINITY, depth = 0): string {
  const pad = (d: number) => "  ".repeat(d);
  const inline = depth >= inlineFrom;
  const wrap = (parts: string[], open: string, close: string) =>
    inline
      ? `${open}${parts.join(", ")}${close}`
      : `${open}\n${parts.map((p) => pad(depth + 1) + p).join(",\n")}\n${pad(depth)}${close}`;

  if (Array.isArray(value)) {
    if (value.length === 0) return "[]";
    return wrap(
      value.map((v) => stableJson(v, inlineFrom, depth + 1)),
      "[",
      "]",
    );
  }
  if (value !== null && typeof value === "object") {
    const entries = Object.entries(value as Record<string, unknown>).sort(([a], [b]) =>
      a < b ? -1 : a > b ? 1 : 0,
    );
    if (entries.length === 0) return "{}";
    return wrap(
      entries.map(([k, v]) => `${JSON.stringify(k)}: ${stableJson(v, inlineFrom, depth + 1)}`),
      "{",
      "}",
    );
  }
  return JSON.stringify(value) ?? "null";
}

// ───────────────────────────── login-key.json ───────────────────────────────

interface LoginCase {
  name: string;
  /** What this case would catch. Travels with the vector into the Go suite. */
  note: string;
  email: string;
  password: string;
}

/**
 * Chosen for what each one catches in a fresh implementation, not for coverage
 * of the input space — every case here is a mistake somebody makes once.
 */
const LOGIN_CASES: readonly LoginCase[] = [
  {
    name: "basic",
    note: "the shape every other case varies from",
    email: "eric@bullmoose.cc",
    password: "correct horse battery staple",
  },
  {
    name: "mixed-case-email",
    note: "salt lower-cases the address — this MUST derive the same key as `basic`, and a port that skips it fails login with a correct password",
    email: "Eric@Bullmoose.CC",
    password: "correct horse battery staple",
  },
  {
    name: "plus-tagged-email",
    note: "the `+` tag is part of the address and is NOT stripped — a port that 'normalises' it derives a key for a different account",
    email: "eric+cli@bullmoose.cc",
    password: "correct horse battery staple",
  },
  {
    name: "unicode-email-turkish-dotted-i",
    note: "the salt is defined by JS `String.prototype.toLowerCase`, which is FULL case mapping: U+0130 becomes 'i' + U+0307 (two code points). Go's `strings.ToLower` yields a bare 'i' and derives a different salt — verified, not hypothetical",
    email: "İrem@Bullmoose.CC",
    password: "correct horse battery staple",
  },
  {
    name: "unicode-password",
    note: "the password is UTF-8 encoded, including astral-plane code points — a port that treats it as Latin-1 or as UTF-16 units diverges",
    email: "eric@bullmoose.cc",
    password: "pässwörd–日本語–🔑",
  },
  {
    name: "empty-password",
    note: "PBKDF2 with a zero-length key; HMAC implementations sometimes special-case an empty key, and the UI layer sometimes refuses to send one",
    email: "eric@bullmoose.cc",
    password: "",
  },
  {
    name: "long-password",
    note: "longer than HMAC-SHA256's 64-byte block, so the key is pre-hashed before use — the branch a short password never reaches",
    email: "eric@bullmoose.cc",
    password: "correct horse battery staple ".repeat(20),
  },
];

async function loginKeyVectors() {
  const vectors = [];
  for (const c of LOGIN_CASES) {
    // Sequential rather than Promise.all: 600k iterations apiece, and a
    // deterministic order is worth more here than a few hundred milliseconds.
    vectors.push({
      ...c,
      saltHex: await loginSaltHex(c.email),
      loginKey: await deriveLoginKey(c.email, c.password),
    });
  }
  return {
    $comment: EDIT_WARNING,
    source: "packages/auth-core/src/index.ts:241 deriveLoginKey",
    algo: LOGIN_KEY_ALGO,
    // The parameters, not just the outputs. A port that matches every key below
    // while stretching 10k times passes today and breaks the moment a vector is
    // regenerated — and the failure would look like a bad password.
    iterations: LOGIN_KEY_ITERATIONS,
    saltLabel: LOGIN_SALT_LABEL,
    // Measured off a real key rather than restated from the `256` literal in
    // `deriveBits`, so the two can never disagree.
    keyBits: ((vectors[0]?.loginKey.length ?? 0) / 2) * 8,
    /** `salt = SHA-256(saltLabel + lowercase(email))`, recorded so a mismatch
     * localises to the salt or to the stretch instead of to "login is broken". */
    vectors,
  };
}

// ─────────────────────────────── scopes.json ────────────────────────────────

/**
 * Every `(granted[], required)` pair over the full vocabulary — the whole
 * product, not a sample. `webmail/src/lib/console/scopes.test.ts:32` already
 * checks its mirror this way ("every singleton, every pair, plus the bundle
 * cases"); this is that suite's universe, emitted instead of asserted.
 *
 * `"nonsense"` is in the universe on purpose: `hasScope` denies unknown strings
 * unless held verbatim (auth-core index.ts:107), and "fail closed" is exactly
 * the rule a fresh implementation is most likely to get wrong.
 */
function scopeVectors() {
  const universe = [...MAIL_SCOPES, ...REALM_SCOPES, "mail", "admin", "nonsense"];
  const lists: string[][] = [[], ...universe.map((s) => [s])];
  for (const a of universe) for (const b of universe) lists.push([a, b]);

  const cases: { granted: string[]; required: string; ok: boolean }[] = [];
  for (const granted of lists) {
    for (const required of universe) {
      cases.push({ granted, required, ok: hasScope(granted, required) });
    }
  }

  return {
    $comment: EDIT_WARNING,
    source: "packages/auth-core/src/index.ts:107 hasScope",
    // The four declarations `packages/cli/src/scopes.test.ts:141` currently
    // regex-parses out of auth-core's source text. Recorded here so that hack
    // has a generated artefact to read instead.
    vocabulary: {
      mailScopes: [...MAIL_SCOPES],
      realmScopes: [...REALM_SCOPES],
      tokenScopes: [...TOKEN_SCOPES],
      selfServiceScopes: [...SELF_SERVICE_SCOPES],
      defaultLoginScopes: [...DEFAULT_LOGIN_SCOPES],
    },
    universe,
    cases,
  };
}

// ────────────────────────────── exit-codes.json ─────────────────────────────

/**
 * `EXIT` and the whole `JMAP_EXIT` table. These are a public interface — a
 * script branches on them — so they may be added to but never redefined
 * (`packages/cli/src/io.ts:52`), which is the definition of something worth
 * pinning across an implementation swap.
 */
function exitCodeVectors() {
  return {
    $comment: EDIT_WARNING,
    source: "packages/cli/src/io.ts:52 EXIT, :96 JMAP_EXIT",
    exit: { ...EXIT },
    jmapType: { ...JMAP_EXIT },
    // The fallbacks, from the real function rather than from its doc comment:
    // "anything unlisted falls to 1" is half the table's behaviour, and a port
    // that defaulted to 2 would pass every listed case.
    unlistedJmapType: exitCodeForJmapType("noSuchJmapErrorType"),
    absentJmapType: exitCodeForJmapType(undefined),
  };
}

// ────────────────────────────────────────────────────────────────────────────

/**
 * The exact bytes of each committed file, keyed by name. Pure — the caller
 * decides whether to write them or compare them, so the writer and the drift
 * check can never be checking different things.
 */
export async function buildVectors(): Promise<Record<VectorFile, string>> {
  const text = (value: unknown, inlineFrom?: number) => `${stableJson(value, inlineFrom)}\n`;
  return {
    "exit-codes.json": text(exitCodeVectors()),
    "login-key.json": text(await loginKeyVectors()),
    // Depth 2 is a case object: one line each, ~2.4k lines instead of ~24k.
    "scopes.json": text(scopeVectors(), 2),
  };
}
