components:
  - name: common
  - name: cli
  - name: cloud-infra
    label: "infra"
  - name: agentic-components
    label: "agentic"
  - name: webUI

sources:
  - dir: packages/*
  - dir: services/*
  - dir: tools/*
