package markdown

// Golden baselines for `send --expandMD html`.
//
// These are NOT a comparison against Node — that comparison is impossible here
// and the requirement was loosened on purpose (see the package comment). They
// are a comparison against THIS renderer's agreed output, so a goldmark
// upgrade or an option change that alters outbound mail fails the build
// instead of arriving in someone's inbox.
//
// Update deliberately: `go test ./internal/markdown -update`, then READ the
// diff. A golden file regenerated without reading it protects nothing.

import (
	"flag"
	"os"
	"path/filepath"
	"strings"
	"testing"
)

var update = flag.Bool("update", false, "rewrite the golden files")

func TestRenderGoldens(t *testing.T) {
	cases := map[string]string{
		"headings":   "# One\n\n## Two\n\nbody text\n",
		"emphasis":   "*em* and **strong** and `code`\n",
		"link":       "[bullmoose](https://bullmoose.cc)\n",
		"image":      "![alt](./cat.png)\n",
		"list":       "- a\n- b\n  - nested\n\n1. first\n2. second\n",
		"codeblock":  "```go\nfmt.Println(\"hi\")\n```\n",
		"blockquote": "> quoted\n> still quoted\n",
		"table":      "| a | b |\n|---|---|\n| 1 | 2 |\n",
		"strike":     "~~gone~~\n",
		"tasklist":   "- [ ] todo\n- [x] done\n",
		"autolink":   "see https://bullmoose.cc for more\n",
		// A soft break is a CONTINUATION, not a <br>. Mail clients reflow, and
		// hard-wrapping here turns every 80-column source file into ragged
		// forced breaks.
		"softbreak": "one line\nsecond line\n",
		// The safety case, and the one place this renderer is deliberately
		// STRICTER than marked: the body becomes outbound mail, so raw HTML is
		// escaped rather than passed through.
		"raw_html_is_escaped": "<script>alert(1)</script>\n\n<img src=x onerror=y>\n",
		"entities":            "AT&T -- \"quoted\" & <brackets>\n",
	}

	for name, src := range cases {
		t.Run(name, func(t *testing.T) {
			got, err := ToHTML(src)
			if err != nil {
				t.Fatalf("ToHTML: %v", err)
			}
			path := filepath.Join("testdata", name+".html")
			if *update {
				if err := os.MkdirAll("testdata", 0o755); err != nil {
					t.Fatal(err)
				}
				if err := os.WriteFile(path, []byte(got), 0o644); err != nil {
					t.Fatal(err)
				}
				return
			}
			want, err := os.ReadFile(path)
			if err != nil {
				t.Fatalf("no golden for %q (run with -update, then READ the diff): %v", name, err)
			}
			if got != string(want) {
				t.Errorf("rendering changed for %q.\n--- want ---\n%s\n--- got ---\n%s", name, want, got)
			}
		})
	}
}

func TestRawHTMLIsEscapedNotExecutedAndNotLost(t *testing.T) {
	// Held apart from the goldens because these are the two SECURITY
	// properties, and a golden can be regenerated by someone chasing a diff.
	//
	// Both halves matter, and the second is the one that bit:
	//
	//	NOT EXECUTED — no tag may survive as markup, or a pasted <script> or a
	//	  tracking pixel becomes live in someone else's inbox.
	//	NOT LOST — the text must still be THERE, escaped. goldmark's default is
	//	  to DELETE raw HTML, which silently removes "use <brackets> like this"
	//	  from a body and tells the sender nothing.
	//
	// The first version of this test asserted on the substring "onerror=" and
	// FAILED once escaping was correct — the escaped output contains those
	// characters as harmless visible text. Asserting on substrings tests the
	// bytes; the property is about MARKUP.
	for _, tc := range []struct{ src, mustEscape string }{
		{`<script>alert(1)</script>`, "&lt;script&gt;"},
		{`<img src=x onerror=alert(1)>`, "&lt;img"},
		{`<iframe src="https://evil.test"></iframe>`, "&lt;iframe"},
		{`a <b>bold</b> claim`, "&lt;b&gt;"},
		{`use <brackets> like this`, "&lt;brackets&gt;"},
	} {
		got, err := ToHTML(tc.src)
		if err != nil {
			t.Fatalf("ToHTML(%q): %v", tc.src, err)
		}
		// No tag opener survives except the wrapper goldmark emits itself.
		for _, tag := range []string{"<script", "<img", "<iframe", "<b>", "<brackets"} {
			if strings.Contains(got, tag) {
				t.Errorf("markup survived: %q produced %q (contains %q)", tc.src, got, tag)
			}
		}
		// And it was escaped rather than dropped.
		if !strings.Contains(got, tc.mustEscape) {
			t.Errorf("text was LOST, not escaped: %q produced %q (want %q)", tc.src, got, tc.mustEscape)
		}
	}
}
